// <auto-generated />
using System;
using FlashCardLearning.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashCardLearning.Migrations
{
    [DbContext(typeof(FlashCardAppContext))]
    [Migration("20250314191047_UpdatedDBConnectionString")]
    partial class UpdatedDBConnectionString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlashCardLearning.Model.FlashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlashCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8e5d29a-6d67-4c76-8cc7-c444f3e6f5b8"),
                            Description = "a card",
                            Name = "card 1",
                            type = "Text"
                        },
                        new
                        {
                            Id = new Guid("e363572b-b54b-433d-a001-2e1252c81852"),
                            Description = "a card",
                            Name = "card 2",
                            type = "Text"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
