// <auto-generated />
using System;
using FlashCardLearning.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashCardLearning.Migrations
{
    [DbContext(typeof(FlashCardAppContext))]
    [Migration("20250314190422_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlashCardLearning.Model.FlashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlashCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("adda961e-ff99-4d86-920f-43ee64c8d657"),
                            Description = "a card",
                            Name = "card 1",
                            type = "Text"
                        },
                        new
                        {
                            Id = new Guid("2bf7da17-ef05-4357-8999-75329f695acb"),
                            Description = "a card",
                            Name = "card 2",
                            type = "Text"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
